### ISSUE TITLE
Max window size

### ISSUE THREAD

**Issue by Kenan7** [TanisukeGoro/Wipeyy#23]
First I want to say that this extension is great, I use it for watching tutorials & edit code at the same time. 
But I want to resize it, I think it is limited for 1/4 of the screen or whatever?
Anyway, let me know if it's possible to do so. Keep it up🤗

**Comment by TanisukeGoro** [comment]
Thanks for the first issue and for using this extension!
The screen size is fixed by Chrome, so I don't know how to change it. We probably can't. I will try it is possible or not.

Anyway, I'm going to make some major changes in the past month to make this extension easier to use. 
I hope you'll be looking forward to it!

**Comment by Kenan7** [comment]
Yes, of course, I tried near to 8 extensions and I liked this one because I have more control over it, pause, skip seconds so on.
